Feature/task 5
daria-veselkova/learn-homework-1 pull request #3
Opened 2021-11-24 14:24 UTC by daria-veselkova

2021-11-25 08:20 UTC, vppuzakov requested changes
Работает, но есть что улучшить по производительности

2021-11-25 08:20 UTC, vppuzakov commented on 5_while2.py
> +      user_question = input("Спроси меня о чем-нибудь: ").capitalize().strip()
💡 надежнее к `lower()` приводить, чем `capitalize()`, мы называем это в Natural Language Processing задачах препроцессингом текста.

Но тогда надо будет и словарик к lower привести

2021-11-25 08:20 UTC, vppuzakov commented on 5_while2.py
> +      if user_question in questions_and_answers.keys():
🔴  лучше использовать `question in questions` без .keys() части

Дело в том, что keys() возращает список и происходит поиск перебором O(n). Поиск же ключа в словаре имеет O(1) сложность

2021-11-25 08:20 UTC, vppuzakov commented on 5_while2.py
> +      if user_question in questions_and_answers.keys():
Еще лучше здесь воспользоваться методом `.get`

```python
answer = questions.get(question)
if not answer:
    print('ask something else')
    break
    
if answer == 'stop': ...
```

2021-11-25 16:32 UTC, daria-veselkova commented on 5_while2.py
> +      user_question = input("Спроси меня о чем-нибудь: ").capitalize().strip()
Оо, до меня дошло. capitalize() решит только проблему первой буквы, но ведь бывают любители писать заглавные в середине слова . lower() же всю строку приводит к одному регистру. Исправлю, спасибо!

2021-11-26 07:33 UTC, daria-veselkova commented on 5_while2.py
> +      if user_question in questions_and_answers.keys():
Оо, я забыла про get и про in! С математикой у меня все также туго, но суть O-notation я вроде бы поняла. Теперь понимаю, почему нехорошо вкладывать ифы и циклы и чем плохо искать ключ через .keys(). Круто, спасибо! 
Поправила задание + посмотрела разницы во времени исполнения функции, если проверка на наличие ключа в словаре осуществляется разными способами. Через ib быстрее всего, но в задаче get, чтобы, как ты и указал, сделать запрос только один раз

2021-12-01 22:06 UTC, vppuzakov approved these changes
👍

2021-12-01 22:06 UTC, vppuzakov commented on 5_while2.py
> +        answer = questions_and_answers.get(user_question)
👍 все верно

2021-12-01 22:06 UTC, vppuzakov commented on test.py
> +print(timeit.timeit(lambda: ask_user_1('Как дела?')))
👍 классно, что получилось потестить еще и время исполнения.

2021-12-02 07:32 UTC, merged